//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employe()
        {
            this.WorkDays = new HashSet<WorkDay>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ING { get; set; }
        public Nullable<int> ShedulesId { get; set; }
        public Nullable<bool> Show { get; set; }
    
        public virtual Shedule Shedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDay> WorkDays { get; set; }
    }
}
